### ISSUE TITLE
Approach to encode sequence position in DOM is rather fragile.

### ISSUE THREAD

**Issue by yeban** [ljgarcia/biojs-vis-sequence#12]
If the sequence id is '123456', `span` element are given the id '123456_n' where 'n' is [0, sequence length - 1]. And position is inferred later (like in [L1294](https://github.com/ljgarcia/biojs-vis-sequence/blob/master/lib/index.js#L1294)) by reading after `_`.

This breaks for the simplest of the use cases. For example if sequence id itself contains an `_`, which is quite common.

Workaround is to not pass sequence id to `Sequence` constructor and disable title, or strip sequence id of `_` before passing to `Sequence`.

A possible solution is to use `data-` attributes to remember position.

**Comment by ljgarcia** [comment]
This component works with protein sequences. Rather than a protein id, it is meant to get a protein accession as defined by UniProt. In UniProt accessions do not have "_". Still, an easy fix is to localize the last "_" in the span element id, rather that the first one.

**Comment by yeban** [comment]
Can this component not be used with nucleotide sequences?

**Comment by ljgarcia** [comment]
Potentially, yes, there is no restriction on whar the sequence actually
represents.  However, I do not recall whether it was tested with such long
sequences. Have you try it with nucleotide sequences? If so, please let us
know how it works for you, and how useful it is in its current state.

**Comment by yeban** [comment]
Yup. We are using biojs-vis-sequence for [SequenceServer](http://www.sequenceserver.com/).

We are working on a complete revamp and decided to use biojs-vis-sequence for visualising sequences. Here's a demo - http://antgenomes.org/sequenceserver/.

Use
```
>SI2.2.0_06267 locus=Si_gnF.scaffold02592[1282609..1284114].pep_2 quality=100.00
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIR
TNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITD
ITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGE
KENKIKEGMKMMGLNDSVF
```
against `Solenopsis invicta predicted transcripts 2.2.3` database to get a guaranteed hit. Scroll down to a hit and select 'View Sequence'.

We disable visualization for sequences bigger than 10k chars. Will probably up the number after some experimenting.

The current feature set is looking very useful for our needs. #7 is a major showstopper for us though.

**Comment by greenify** [comment]
Hey does 2e51011a27a5c36d13882955881b4786fb387d22 fix your problem?

**Comment by ljgarcia** [comment]
Let's wait for Anurag saying whether it works or not. But, are we sure it
does not break anything? I kind of like more looking for the last "_"
rather for the first one, because the last one for sure was the one added
with the sequence position.

**Comment by yeban** [comment]
It works. Thanks.

I had mentioned in my first comment that not passing `id` to the widget works, and I had been doing just that to work around the issue till now. I realise now that if two instance of `Sequence` widgets were initialised on a page, the workaround would have created more than one element with the same id on the same page. Duplicate id for `span` elements [doesn't get in the way of working of the widget](https://github.com/ljgarcia/biojs-vis-sequence/blob/master/lib/index.js#L554), but is semantically incorrect. @greenify's commit takes care of that.

**Comment by yeban** [comment]
@ljgarcia In the broader scope of things, where the widget is not just confined to Uniprot sequences, many funky characters may be present in the sequence id. I wonder if deriving id for DOM elements using sequence id (by adding _n to them) would be a good idea in that case.
