### ISSUE TITLE
The user cannot select text for copying

### ISSUE THREAD

**Issue by alexkalderimis** [ljgarcia/biojs-vis-sequence#7]
One of the things users will want to do is select text for standard copy/paste functionality. This is being blocked by this component, and should be enabled.

**Comment by yeban** [comment]
Perhaps an option to disable selection with mouse can be a quick (and dirty) workaround?

**Comment by yannickwurm** [comment]
+1

**Comment by greenify** [comment]
Hey I just wrote the small module [copy2clipboard](https://github.com/greenify/copy2clipboard). It allows to copy to the user clipboard without using any dirty flash hacks. 

I hope this is better than a dirty workaround ;-)

**Comment by ljgarcia** [comment]
Great Seb, thanks!

**Comment by yeban** [comment]
I'm sorry, this doesn't seem to work on my Mac. Could it be because the shortcut to copy on Mac is "Cmd-C"?

**Comment by yeban** [comment]
I just took a quick look at 'copy2clipboard'. Binding to `Ctrl-C` means user can't select 'Edit -> Copy', or 'Right click -> Copy'. This doesn't conform to user's expectations. And as pointed above, this doesn't work on Mac.

Perhaps a solution could be in creating a [`Range`](http://www.quirksmode.org/dom/range_intro.html) object and [making it visible to user as a normal selection](http://stackoverflow.com/questions/1426634/make-programmatic-range-selection-visible-to-the-user).

**Comment by yeban** [comment]
It also seems to interfere with other shortcuts on Mac. After highlighting a portion of a sequence and pressing 'Ctrl-C' or 'Cmd-C', 'Cmd-A' shortcut to select all content doesn't work anymore on the same page. It works if I revert 'biojs-vis-sequence' to the previous version.
